name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - flask
  - mysql-connector-python
  - pandas
  - fpdf
  - python-dateutil
  - requests
  - numpy
  - pyopenssl  # Ensure OpenSSL bindings are installed
  - pip
  - pip:
      - cryptography  # Optional for extra security
