name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps: 
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Add Conda to system path
      run: echo $CONDA/bin >> $GITHUB_PATH

    - name: Cache Conda Packages
      uses: actions/cache@v3
      with:
        path: ~/conda_pkgs_dir
        key: conda-${{ runner.os }}-${{ hashFiles('environment.yml') }}
        restore-keys: conda-${{ runner.os }}-

    - name: Create Conda Environment
      run: |
        conda env create --file environment.yml --name myenv
      shell: bash -l {0}

    - name: Install additional dependencies
      run: |
        conda run -n myenv conda install flake8 pytest
      shell: bash -l {0}

    - name: Lint with flake8
      run: |
        conda run -n myenv flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        conda run -n myenv flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      shell: bash -l {0}

    - name: Test with pytest
      run: |
        conda run -n myenv pytest
      shell: bash -l {0}
